import { Inter } from 'next/font/google'
import './globals.css'
import TailMenu from './component/comm/TailMenu'
import TailFooter from './component/comm/TailFooter'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App K-digital',
  description: 'K-digital project : Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col w-full max-w-screen-xl mx-auto h-screen">
        <TailMenu/>
        <main className='grow flex flex-col justify-center items-center'>
          {children}
        </main>
        <TailFooter/>
      </body>
    </html>
  )
}
